{% set name = "opentelemetry-instrumentation-logging" %}
{% set version = "0.25b1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-logging-{{ version }}.tar.gz
  sha256: 5eece14bdf296ffc2d2807e3e7de08fbeb994c9ac63f52a2e9241d4b0e7ae3f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.25b1
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-test ==0.25b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/master/instrumentation/opentelemetry-instrumentation-logging
  summary: OpenTelemetry Logging instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
