{% set name = "opentelemetry-instrumentation-logging" %}
{% set version = "0.30b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-instrumentation-logging-{{ version }}.tar.gz
  sha256: 2d9a1adb96d95151e67c6a92c2e6aaa99175d2a0fe510407d266a03943a2ea3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - opentelemetry-instrumentation ==0.30b0
    - python >=3.6
    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test ==0.25b0
    # - opentelemetry-test ==0.25b1
    # - opentelemetry-test ==0.25b2
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-test-utils ==0.28b0
    # - opentelemetry-test-utils ==0.28b1
    # - opentelemetry-test-utils ==0.29b0
    # - opentelemetry-test-utils ==0.30b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/master/instrumentation/opentelemetry-instrumentation-logging
  summary: OpenTelemetry Logging instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
