{% set name = "opentelemetry-instrumentation-logging" %}
{% set version = "0.58b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 1475e531cf0e1c03e1c42995fcf312767edaadfe335d04d1d3b27c9a8c8c7049

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api >=1.12,<2
    - opentelemetry-instrumentation =={{ version }}

# Tests disabled:
# E   ModuleNotFoundError: No module named 'opentelemetry.test'
# https://pypi.org/project/opentelemetry-test-utils, not in the main channel.
test:
  imports:
    - opentelemetry.instrumentation.logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/master/instrumentation/opentelemetry-instrumentation-logging
  summary: OpenTelemetry Logging instrumentation
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    The OpenTelemetry logging integration automatically injects tracing context into log statements.
  dev_url: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-logging
  doc_url: https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/logging/logging.html

extra:
  recipe-maintainers:
    - mariusvniekerk
  skip-lints:
    - documentation_specifies_language
